-- BhuDrishti core schema. Idempotent: safe to re-run.
-- Writes happen server-side with the service-role key (bypasses RLS).
-- Browsers use the anon key for Realtime/read-only views, constrained by RLS below.

-- ── events (telemetry decisions). Extends the original supabase/events.sql table. ──
create table if not exists public.events (
  id text primary key,
  node_id text not null,
  node_name text not null,
  lat double precision not null,
  lng double precision not null,
  recorded_at timestamptz not null,
  source text not null check (source in ('esp32_node', 'phone_layer')),
  confirmation text not null,
  classification text not null check (classification in ('normal', 'event')),
  confidence double precision not null check (confidence >= 0 and confidence <= 1),
  features jsonb not null,
  telemetry jsonb not null,
  created_at timestamptz not null default now()
);
alter table public.events add column if not exists device_id text;
alter table public.events add column if not exists received_at timestamptz;
alter table public.events add column if not exists channel text not null default 'unknown';
alter table public.events add column if not exists transport text not null default 'unknown';
alter table public.events add column if not exists queued boolean not null default false;
alter table public.events add column if not exists client_event_id text;
alter table public.events add column if not exists alert_confidence double precision not null default 0;
alter table public.events add column if not exists quality jsonb not null default '{}'::jsonb;
alter table public.events add column if not exists cross_confirmation jsonb not null default '{}'::jsonb;
alter table public.events add column if not exists is_demo boolean not null default false;

create index if not exists events_recorded_at_idx on public.events (recorded_at desc);
create index if not exists events_node_id_idx on public.events (node_id);
create index if not exists events_node_recorded_idx on public.events (node_id, recorded_at desc);
create index if not exists events_event_only_idx on public.events (recorded_at desc) where classification = 'event';
create unique index if not exists events_client_event_id_uidx on public.events (client_event_id) where client_event_id is not null;

-- ── device / node registry ──
create table if not exists public.devices (
  id text primary key,
  name text not null,
  kind text not null default 'esp32' check (kind in ('esp32', 'phone', 'gateway', 'other')),
  source text not null default 'esp32_node' check (source in ('esp32_node', 'phone_layer')),
  lat double precision,
  lng double precision,
  status text not null default 'unknown',
  battery_pct double precision check (battery_pct is null or (battery_pct >= 0 and battery_pct <= 100)),
  last_seen timestamptz,
  range_km double precision check (range_km is null or range_km > 0),
  reliability double precision check (reliability is null or (reliability >= 0 and reliability <= 1)),
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists devices_last_seen_idx on public.devices (last_seen desc);

-- ── ingestion log (accepted / duplicate / rejected) ──
create table if not exists public.ingestion_logs (
  id text primary key,
  received_at timestamptz not null default now(),
  outcome text not null check (outcome in ('accepted', 'duplicate', 'rejected')),
  node_id text,
  device_id text,
  source text,
  channel text,
  client text,
  detail text,
  event_id text,
  queued boolean not null default false
);
create index if not exists ingestion_logs_received_idx on public.ingestion_logs (received_at desc);

-- ── alerts (human approval required before any public notification) ──
create table if not exists public.alerts (
  id text primary key,
  node_id text not null,
  node_name text not null,
  lat double precision,
  lng double precision,
  level text not null check (level in ('advisory', 'watch', 'warning')),
  status text not null check (status in ('open', 'pending_approval', 'approved', 'rejected', 'resolved')),
  requires_approval boolean not null default true,
  confidence double precision not null default 0 check (confidence >= 0 and confidence <= 1),
  sources text[] not null default '{}',
  event_ids text[] not null default '{}',
  decided_by text,
  decision_note text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists alerts_status_idx on public.alerts (status, updated_at desc);

-- ── model decisions (one row per classification) ──
create table if not exists public.model_decisions (
  id bigint generated by default as identity primary key,
  event_id text not null,
  model text not null,
  label text not null,
  confidence double precision not null,
  features jsonb not null,
  quality_flags text[] not null default '{}',
  created_at timestamptz not null default now()
);
create index if not exists model_decisions_event_idx on public.model_decisions (event_id);

-- ── coverage snapshots ──
create table if not exists public.coverage_samples (
  id bigint generated by default as identity primary key,
  as_of timestamptz not null,
  max_age_minutes double precision not null,
  summary jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists coverage_samples_as_of_idx on public.coverage_samples (as_of desc);

-- ── audit trail for privileged actions ──
create table if not exists public.audit_events (
  id text primary key,
  at timestamptz not null default now(),
  action text not null,
  actor text not null,
  target text,
  detail jsonb not null default '{}'::jsonb
);
create index if not exists audit_events_at_idx on public.audit_events (at desc);

-- ── notifications (drafts and approved messages) ──
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  alert_id text references public.alerts (id) on delete set null,
  lang text not null default 'en',
  body text not null,
  status text not null default 'draft' check (status in ('draft', 'approved', 'sent', 'failed', 'cancelled')),
  provider text,
  created_at timestamptz not null default now()
);

-- ── translation cache ──
create table if not exists public.translations (
  cache_key text primary key,
  source_lang text not null,
  target_lang text not null,
  source_text text not null,
  translated_text text not null,
  provider text not null,
  created_at timestamptz not null default now()
);

-- ── agent runs (provenance for every advisory output) ──
create table if not exists public.agent_runs (
  id text primary key,
  started_at timestamptz not null,
  finished_at timestamptz,
  event_id text,
  requested_by text,
  providers_used text[] not null default '{}',
  requires_approval boolean not null default false,
  result jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists agent_runs_started_idx on public.agent_runs (started_at desc);

-- ── updated_at trigger ──
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists devices_touch on public.devices;
create trigger devices_touch before update on public.devices for each row execute function public.touch_updated_at();
